name: Update Online File

on:
  schedule:
    - cron: '*/10 * * * *'  # Каждые 10 минут

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./.github/actions/checkout

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_online.py
